<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE graph [
<!ELEMENT graph (data-type, display+, node+, edge+)>
<!ELEMENT data-type (#PCDATA)>
<!ELEMENT display (node-color, edge-color, max-edge-width)>
<!ELEMENT node-color (#PCDATA)>
<!ELEMENT edge-color (#PCDATA)>
<!ELEMENT max-edge-width (#PCDATA)>
<!ELEMENT node (id, super-node, label, weight, type)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT super-node (#PCDATA)>
<!ELEMENT label (#PCDATA)>
<!ELEMENT edge (from, to, type, weight)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT weight (#PCDATA)>
]>
<graph>
<data-type>file-system</data-type>
<display>
	<node-color>0,0,255</node-color>
	<edge-color>100,100,100</edge-color>
	<max-edge-width>40</max-edge-width>
</display>
<node>
	<id>0</id>
	<super-node>false</super-node>
	<label>.</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>1</id>
	<super-node>false</super-node>
	<label>Assignments</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>2</id>
	<super-node>false</super-node>
	<label>Assignment1.doc</label>
	<weight>44</weight>
	<type>0</type>
</node>
<node>
	<id>3</id>
	<super-node>false</super-node>
	<label>Assignment1.pdf</label>
	<weight>231</weight>
	<type>0</type>
</node>
<node>
	<id>4</id>
	<super-node>false</super-node>
	<label>Good Work</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>5</id>
	<super-node>false</super-node>
	<label>WorksFromStudents-Assignment 1</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>6</id>
	<super-node>false</super-node>
	<label>18687330 LAU Chng Wei</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>7</id>
	<super-node>false</super-node>
	<label>.DS_Store</label>
	<weight>12</weight>
	<type>-1</type>
</node>
<node>
	<id>8</id>
	<super-node>false</super-node>
	<label>D_CTreemap</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>9</id>
	<super-node>false</super-node>
	<label>.DS_Store</label>
	<weight>8</weight>
	<type>-1</type>
</node>
<node>
	<id>10</id>
	<super-node>false</super-node>
	<label>data</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>11</id>
	<super-node>false</super-node>
	<label>.DS_Store</label>
	<weight>6</weight>
	<type>-1</type>
</node>
<node>
	<id>12</id>
	<super-node>false</super-node>
	<label>1345.xml</label>
	<weight>293</weight>
	<type>0</type>
</node>
<node>
	<id>13</id>
	<super-node>false</super-node>
	<label>13936.xml</label>
	<weight>3109</weight>
	<type>0</type>
</node>
<node>
	<id>14</id>
	<super-node>false</super-node>
	<label>6001.xml</label>
	<weight>1325</weight>
	<type>0</type>
</node>
<node>
	<id>15</id>
	<super-node>false</super-node>
	<label>programnormal.jar</label>
	<weight>560</weight>
	<type>4</type>
</node>
<node>
	<id>16</id>
	<super-node>false</super-node>
	<label>properties.dat</label>
	<weight>1</weight>
	<type>1</type>
</node>
<node>
	<id>17</id>
	<super-node>false</super-node>
	<label>force-collapsible</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>18</id>
	<super-node>false</super-node>
	<label>.DS_Store</label>
	<weight>8</weight>
	<type>-1</type>
</node>
<node>
	<id>19</id>
	<super-node>false</super-node>
	<label>.Rhistory</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>20</id>
	<super-node>false</super-node>
	<label>d3</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>21</id>
	<super-node>false</super-node>
	<label>.DS_Store</label>
	<weight>6</weight>
	<type>-1</type>
</node>
<node>
	<id>22</id>
	<super-node>false</super-node>
	<label>d3.geom.js</label>
	<weight>22</weight>
	<type>-1</type>
</node>
<node>
	<id>23</id>
	<super-node>false</super-node>
	<label>d3.js</label>
	<weight>126</weight>
	<type>-1</type>
</node>
<node>
	<id>24</id>
	<super-node>false</super-node>
	<label>d3.layout.js</label>
	<weight>48</weight>
	<type>-1</type>
</node>
<node>
	<id>25</id>
	<super-node>false</super-node>
	<label>d3.min.js</label>
	<weight>151</weight>
	<type>-1</type>
</node>
<node>
	<id>26</id>
	<super-node>false</super-node>
	<label>LICENSE</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>27</id>
	<super-node>false</super-node>
	<label>doc.json</label>
	<weight>293</weight>
	<type>-1</type>
</node>
<node>
	<id>28</id>
	<super-node>false</super-node>
	<label>download.json</label>
	<weight>62</weight>
	<type>-1</type>
</node>
<node>
	<id>29</id>
	<super-node>false</super-node>
	<label>force-collapsible demo v2.html</label>
	<weight>16</weight>
	<type>3</type>
</node>
<node>
	<id>30</id>
	<super-node>false</super-node>
	<label>large.json</label>
	<weight>678</weight>
	<type>-1</type>
</node>
<node>
	<id>31</id>
	<super-node>false</super-node>
	<label>README.txt</label>
	<weight>1</weight>
	<type>0</type>
</node>
<node>
	<id>32</id>
	<super-node>false</super-node>
	<label>traverse.py</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>33</id>
	<super-node>false</super-node>
	<label>tson.py</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>34</id>
	<super-node>false</super-node>
	<label>sampleReport1blind.pdf</label>
	<weight>431</weight>
	<type>0</type>
</node>
<node>
	<id>35</id>
	<super-node>false</super-node>
	<label>sampleReport2blind.pdf</label>
	<weight>1782</weight>
	<type>0</type>
</node>
<node>
	<id>36</id>
	<super-node>false</super-node>
	<label>sampleReport3blind.pdf</label>
	<weight>1325</weight>
	<type>0</type>
</node>
<node>
	<id>37</id>
	<super-node>false</super-node>
	<label>WorksFromStudents-Assignment 2</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>38</id>
	<super-node>false</super-node>
	<label>301112 - Assignment 2 - 18687330 LAU Chng Wei</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>39</id>
	<super-node>false</super-node>
	<label>.DS_Store</label>
	<weight>6</weight>
	<type>-1</type>
</node>
<node>
	<id>40</id>
	<super-node>false</super-node>
	<label>Assignment 2 - Report - 18687330 LAU Chng Wei.docx</label>
	<weight>11133</weight>
	<type>0</type>
</node>
<node>
	<id>41</id>
	<super-node>false</super-node>
	<label>Assignment 2 - Report - 18687330 LAU Chng Wei.pdf</label>
	<weight>5609</weight>
	<type>0</type>
</node>
<node>
	<id>42</id>
	<super-node>false</super-node>
	<label>corcrime.csv</label>
	<weight>2</weight>
	<type>0</type>
</node>
<node>
	<id>43</id>
	<super-node>false</super-node>
	<label>Crimb03-12.xlsx</label>
	<weight>28802</weight>
	<type>0</type>
</node>
<node>
	<id>44</id>
	<super-node>false</super-node>
	<label>CrimeT.xlsx</label>
	<weight>46</weight>
	<type>0</type>
</node>
<node>
	<id>45</id>
	<super-node>false</super-node>
	<label>R-code.R</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>46</id>
	<super-node>false</super-node>
	<label>Readme.rtf</label>
	<weight>1</weight>
	<type>0</type>
</node>
<node>
	<id>47</id>
	<super-node>false</super-node>
	<label>ScatterPlot Analysis.twb</label>
	<weight>149</weight>
	<type>-1</type>
</node>
<node>
	<id>48</id>
	<super-node>false</super-node>
	<label>TableauAnalysis.twb</label>
	<weight>809</weight>
	<type>-1</type>
</node>
<node>
	<id>49</id>
	<super-node>false</super-node>
	<label>Bjorn_Rostron_15942337_Assessment2</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>50</id>
	<super-node>false</super-node>
	<label>AllDeathsXyear1919.png</label>
	<weight>68</weight>
	<type>2</type>
</node>
<node>
	<id>51</id>
	<super-node>false</super-node>
	<label>AllDeathsXyear1944.png</label>
	<weight>80</weight>
	<type>2</type>
</node>
<node>
	<id>52</id>
	<super-node>false</super-node>
	<label>Assessment2.twb</label>
	<weight>215</weight>
	<type>-1</type>
</node>
<node>
	<id>53</id>
	<super-node>false</super-node>
	<label>Assessment2_Report.pdf</label>
	<weight>618</weight>
	<type>0</type>
</node>
<node>
	<id>54</id>
	<super-node>false</super-node>
	<label>Flu_age_1919.png</label>
	<weight>57</weight>
	<type>2</type>
</node>
<node>
	<id>55</id>
	<super-node>false</super-node>
	<label>GRIMdatagovau2.csv</label>
	<weight>27549</weight>
	<type>0</type>
</node>
<node>
	<id>56</id>
	<super-node>false</super-node>
	<label>Heart Disease_sex_gender.png</label>
	<weight>41</weight>
	<type>2</type>
</node>
<node>
	<id>57</id>
	<super-node>false</super-node>
	<label>Influenza.png</label>
	<weight>224</weight>
	<type>2</type>
</node>
<node>
	<id>58</id>
	<super-node>false</super-node>
	<label>Line_Graph_ALL_DeathsXyear.png</label>
	<weight>54</weight>
	<type>2</type>
</node>
<node>
	<id>59</id>
	<super-node>false</super-node>
	<label>RespiratorySystemXyear.png</label>
	<weight>103</weight>
	<type>2</type>
</node>
<node>
	<id>60</id>
	<super-node>false</super-node>
	<label>Lesley Mallows - 18767663</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>61</id>
	<super-node>false</super-node>
	<label>Book2.twb</label>
	<weight>899</weight>
	<type>-1</type>
</node>
<node>
	<id>62</id>
	<super-node>false</super-node>
	<label>Crosstab1.xlsx</label>
	<weight>9</weight>
	<type>0</type>
</node>
<node>
	<id>63</id>
	<super-node>false</super-node>
	<label>CrosstabDV.mdb</label>
	<weight>139</weight>
	<type>-1</type>
</node>
<node>
	<id>64</id>
	<super-node>false</super-node>
	<label>ForecastvsActual.xlsx</label>
	<weight>10</weight>
	<type>0</type>
</node>
<node>
	<id>65</id>
	<super-node>false</super-node>
	<label>ForecastvsActual_FromTableau.xlsx</label>
	<weight>10</weight>
	<type>0</type>
</node>
<node>
	<id>66</id>
	<super-node>false</super-node>
	<label>LMallows Assignment 2.docx</label>
	<weight>6893</weight>
	<type>0</type>
</node>
<node>
	<id>67</id>
	<super-node>false</super-node>
	<label>NSW Suburbs.xlsx</label>
	<weight>211</weight>
	<type>0</type>
</node>
<node>
	<id>68</id>
	<super-node>false</super-node>
	<label>NSW_Pop_by_LGA_2001-2011.csv</label>
	<weight>8</weight>
	<type>0</type>
</node>
<node>
	<id>69</id>
	<super-node>false</super-node>
	<label>NSW_Pop_by_LGA_2005-2015.csv</label>
	<weight>16</weight>
	<type>0</type>
</node>
<node>
	<id>70</id>
	<super-node>false</super-node>
	<label>NSW_Pop_by_LGA_2005-2015.xlsx</label>
	<weight>34</weight>
	<type>0</type>
</node>
<node>
	<id>71</id>
	<super-node>false</super-node>
	<label>General</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>72</id>
	<super-node>false</super-node>
	<label>301112_18-AUT_PARR_D-classlist.xls</label>
	<weight>61</weight>
	<type>0</type>
</node>
<node>
	<id>73</id>
	<super-node>false</super-node>
	<label>301112_2018_Autumn_Internal.pdf</label>
	<weight>376</weight>
	<type>0</type>
</node>
<node>
	<id>74</id>
	<super-node>false</super-node>
	<label>Copy of 301112_18-AUT_PARR_D-classlist.xls</label>
	<weight>47</weight>
	<type>0</type>
</node>
<node>
	<id>75</id>
	<super-node>false</super-node>
	<label>desktop.ini</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>76</id>
	<super-node>false</super-node>
	<label>StaffContact.doc</label>
	<weight>30</weight>
	<type>0</type>
</node>
<node>
	<id>77</id>
	<super-node>false</super-node>
	<label>StaffContact.pdf</label>
	<weight>69</weight>
	<type>0</type>
</node>
<node>
	<id>78</id>
	<super-node>false</super-node>
	<label>UnitOutline.pdf</label>
	<weight>378</weight>
	<type>0</type>
</node>
<node>
	<id>79</id>
	<super-node>false</super-node>
	<label>Lecture Notes</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>80</id>
	<super-node>false</super-node>
	<label>InteractionBackup.pptx</label>
	<weight>9230</weight>
	<type>0</type>
</node>
<node>
	<id>81</id>
	<super-node>false</super-node>
	<label>Lecture10Materials</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>82</id>
	<super-node>false</super-node>
	<label>Tableau_Book1.twb</label>
	<weight>47</weight>
	<type>-1</type>
</node>
<node>
	<id>83</id>
	<super-node>false</super-node>
	<label>TabuVis</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>84</id>
	<super-node>false</super-node>
	<label>Data</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>85</id>
	<super-node>false</super-node>
	<label>072313 Sheena Kolla ICS Tu 74-1_cells_found.txt</label>
	<weight>4783</weight>
	<type>0</type>
</node>
<node>
	<id>86</id>
	<super-node>false</super-node>
	<label>CHF_risk_dedup_score2_space.txt</label>
	<weight>136</weight>
	<type>0</type>
</node>
<node>
	<id>87</id>
	<super-node>false</super-node>
	<label>CHW</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>88</id>
	<super-node>false</super-node>
	<label>genomes</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>89</id>
	<super-node>false</super-node>
	<label>250GeneList.csv</label>
	<weight>1</weight>
	<type>0</type>
</node>
<node>
	<id>90</id>
	<super-node>false</super-node>
	<label>AffymetrixAnnotations.csv</label>
	<weight>3391</weight>
	<type>0</type>
</node>
<node>
	<id>91</id>
	<super-node>false</super-node>
	<label>AffymetrixGeneExpression.csv</label>
	<weight>18854</weight>
	<type>0</type>
</node>
<node>
	<id>92</id>
	<super-node>false</super-node>
	<label>genesToProbesets.txt</label>
	<weight>1</weight>
	<type>0</type>
</node>
<node>
	<id>93</id>
	<super-node>false</super-node>
	<label>IlluminaSNP.csv</label>
	<weight>10086</weight>
	<type>0</type>
</node>
<node>
	<id>94</id>
	<super-node>false</super-node>
	<label>SNPAnnotations.csv</label>
	<weight>1791</weight>
	<type>0</type>
</node>
<node>
	<id>95</id>
	<super-node>false</super-node>
	<label>GOI_Microarray.xlsx</label>
	<weight>40</weight>
	<type>0</type>
</node>
<node>
	<id>96</id>
	<super-node>false</super-node>
	<label>GOI_Microarray_20.xlsx</label>
	<weight>9</weight>
	<type>0</type>
</node>
<node>
	<id>97</id>
	<super-node>false</super-node>
	<label>GOI_Microarray_R.xlsx</label>
	<weight>41</weight>
	<type>0</type>
</node>
<node>
	<id>98</id>
	<super-node>false</super-node>
	<label>GOI_Microarray_R_10.txt</label>
	<weight>28</weight>
	<type>0</type>
</node>
<node>
	<id>99</id>
	<super-node>false</super-node>
	<label>GOI_SNP.xlsx</label>
	<weight>28</weight>
	<type>0</type>
</node>
<node>
	<id>100</id>
	<super-node>false</super-node>
	<label>GOI_SNP_R.xlsx</label>
	<weight>13</weight>
	<type>0</type>
</node>
<node>
	<id>101</id>
	<super-node>false</super-node>
	<label>GOI_SNP_R10.txt</label>
	<weight>18</weight>
	<type>0</type>
</node>
<node>
	<id>102</id>
	<super-node>false</super-node>
	<label>GOI_SNP_R10.xlsx</label>
	<weight>29</weight>
	<type>0</type>
</node>
<node>
	<id>103</id>
	<super-node>false</super-node>
	<label>overview1.txt</label>
	<weight>1</weight>
	<type>0</type>
</node>
<node>
	<id>104</id>
	<super-node>false</super-node>
	<label>PatientTreatments.csv</label>
	<weight>4</weight>
	<type>0</type>
</node>
<node>
	<id>105</id>
	<super-node>false</super-node>
	<label>process</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>106</id>
	<super-node>false</super-node>
	<label>PatientTreatments.csv</label>
	<weight>4</weight>
	<type>0</type>
</node>
<node>
	<id>107</id>
	<super-node>false</super-node>
	<label>processedPatientData.csv</label>
	<weight>32</weight>
	<type>0</type>
</node>
<node>
	<id>108</id>
	<super-node>false</super-node>
	<label>processedPatientDataCombined.csv</label>
	<weight>32</weight>
	<type>0</type>
</node>
<node>
	<id>109</id>
	<super-node>false</super-node>
	<label>processedPatientData.csv</label>
	<weight>29</weight>
	<type>0</type>
</node>
<node>
	<id>110</id>
	<super-node>false</super-node>
	<label>processedPatientDataCombined.txt</label>
	<weight>32</weight>
	<type>0</type>
</node>
<node>
	<id>111</id>
	<super-node>false</super-node>
	<label>Collection1</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>112</id>
	<super-node>false</super-node>
	<label>link.txt</label>
	<weight>1</weight>
	<type>0</type>
</node>
<node>
	<id>113</id>
	<super-node>false</super-node>
	<label>DPstatistics.csv</label>
	<weight>1</weight>
	<type>0</type>
</node>
<node>
	<id>114</id>
	<super-node>false</super-node>
	<label>SampleDataSet</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>115</id>
	<super-node>false</super-node>
	<label>Flotation cell-OpenMV.net Datasets.htm</label>
	<weight>14</weight>
	<type>-1</type>
</node>
<node>
	<id>116</id>
	<super-node>false</super-node>
	<label>Flotation cell-OpenMV.net Datasets_files</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>117</id>
	<super-node>false</super-node>
	<label>bootstrap.css</label>
	<weight>117</weight>
	<type>-1</type>
</node>
<node>
	<id>118</id>
	<super-node>false</super-node>
	<label>MathJax.js</label>
	<weight>61</weight>
	<type>-1</type>
</node>
<node>
	<id>119</id>
	<super-node>false</super-node>
	<label>flotation-cell.csv</label>
	<weight>308</weight>
	<type>0</type>
</node>
<node>
	<id>120</id>
	<super-node>false</super-node>
	<label>links.txt</label>
	<weight>1</weight>
	<type>0</type>
</node>
<node>
	<id>121</id>
	<super-node>false</super-node>
	<label>Silicon wafer thickness-OpenMV.net Datasets.htm</label>
	<weight>14</weight>
	<type>-1</type>
</node>
<node>
	<id>122</id>
	<super-node>false</super-node>
	<label>Silicon wafer thickness-OpenMV.net Datasets_files</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>123</id>
	<super-node>false</super-node>
	<label>bootstrap.css</label>
	<weight>117</weight>
	<type>-1</type>
</node>
<node>
	<id>124</id>
	<super-node>false</super-node>
	<label>MathJax.js</label>
	<weight>61</weight>
	<type>-1</type>
</node>
<node>
	<id>125</id>
	<super-node>false</super-node>
	<label>silicon-wafer-thickness-locations.jpg</label>
	<weight>60</weight>
	<type>2</type>
</node>
<node>
	<id>126</id>
	<super-node>false</super-node>
	<label>silicon-wafer-thickness.csv</label>
	<weight>10</weight>
	<type>0</type>
</node>
<node>
	<id>127</id>
	<super-node>false</super-node>
	<label>Solvents-OpenMV.net Datasets.htm</label>
	<weight>14</weight>
	<type>-1</type>
</node>
<node>
	<id>128</id>
	<super-node>false</super-node>
	<label>Solvents-OpenMV.net Datasets_files</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>129</id>
	<super-node>false</super-node>
	<label>bootstrap.css</label>
	<weight>117</weight>
	<type>-1</type>
</node>
<node>
	<id>130</id>
	<super-node>false</super-node>
	<label>MathJax.js</label>
	<weight>61</weight>
	<type>-1</type>
</node>
<node>
	<id>131</id>
	<super-node>false</super-node>
	<label>solvents.csv</label>
	<weight>6</weight>
	<type>0</type>
</node>
<node>
	<id>132</id>
	<super-node>false</super-node>
	<label>Travel times-OpenMV.net Datasets.htm</label>
	<weight>15</weight>
	<type>-1</type>
</node>
<node>
	<id>133</id>
	<super-node>false</super-node>
	<label>Travel times-OpenMV.net Datasets_files</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>134</id>
	<super-node>false</super-node>
	<label>bootstrap.css</label>
	<weight>117</weight>
	<type>-1</type>
</node>
<node>
	<id>135</id>
	<super-node>false</super-node>
	<label>MathJax.js</label>
	<weight>61</weight>
	<type>-1</type>
</node>
<node>
	<id>136</id>
	<super-node>false</super-node>
	<label>travel-times.csv</label>
	<weight>14</weight>
	<type>0</type>
</node>
<node>
	<id>137</id>
	<super-node>false</super-node>
	<label>website-traffic.csv</label>
	<weight>6</weight>
	<type>0</type>
</node>
<node>
	<id>138</id>
	<super-node>false</super-node>
	<label>wood-fibres.csv</label>
	<weight>956</weight>
	<type>0</type>
</node>
<node>
	<id>139</id>
	<super-node>false</super-node>
	<label>Wenbo</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>140</id>
	<super-node>false</super-node>
	<label>Clipboard01.jpg</label>
	<weight>346</weight>
	<type>2</type>
</node>
<node>
	<id>141</id>
	<super-node>false</super-node>
	<label>tasmamoman crashdata_processed.txt</label>
	<weight>40636</weight>
	<type>0</type>
</node>
<node>
	<id>142</id>
	<super-node>false</super-node>
	<label>tasmamoman crashdata_processed_small.txt</label>
	<weight>251</weight>
	<type>0</type>
</node>
<node>
	<id>143</id>
	<super-node>false</super-node>
	<label>Tasmania.jpg</label>
	<weight>366</weight>
	<type>2</type>
</node>
<node>
	<id>144</id>
	<super-node>false</super-node>
	<label>Tasmania1.jpg</label>
	<weight>345</weight>
	<type>2</type>
</node>
<node>
	<id>145</id>
	<super-node>false</super-node>
	<label>Tasmania2.jpg</label>
	<weight>345</weight>
	<type>2</type>
</node>
<node>
	<id>146</id>
	<super-node>false</super-node>
	<label>Tasmania3.jpg</label>
	<weight>344</weight>
	<type>2</type>
</node>
<node>
	<id>147</id>
	<super-node>false</super-node>
	<label>Tasmania4.jpg</label>
	<weight>342</weight>
	<type>2</type>
</node>
<node>
	<id>148</id>
	<super-node>false</super-node>
	<label>TasmaniaT.png</label>
	<weight>564</weight>
	<type>2</type>
</node>
<node>
	<id>149</id>
	<super-node>false</super-node>
	<label>TasmaniaT2.png</label>
	<weight>504</weight>
	<type>2</type>
</node>
<node>
	<id>150</id>
	<super-node>false</super-node>
	<label>wenbo.txt</label>
	<weight>13503</weight>
	<type>0</type>
</node>
<node>
	<id>151</id>
	<super-node>false</super-node>
	<label>wlk_vis_data_abrunker.csv</label>
	<weight>20</weight>
	<type>0</type>
</node>
<node>
	<id>152</id>
	<super-node>false</super-node>
	<label>wlk_vis_data_abrunker.txt</label>
	<weight>15</weight>
	<type>0</type>
</node>
<node>
	<id>153</id>
	<super-node>false</super-node>
	<label>xidan_data</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>154</id>
	<super-node>false</super-node>
	<label>children</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>155</id>
	<super-node>false</super-node>
	<label>VNKR41SV</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>156</id>
	<super-node>false</super-node>
	<label>VNKR41FL.csv</label>
	<weight>1923</weight>
	<type>0</type>
</node>
<node>
	<id>157</id>
	<super-node>false</super-node>
	<label>VNKR41FL.dat</label>
	<weight>1923</weight>
	<type>1</type>
</node>
<node>
	<id>158</id>
	<super-node>false</super-node>
	<label>VNKR41FL.FRQ</label>
	<weight>1065</weight>
	<type>-1</type>
</node>
<node>
	<id>159</id>
	<super-node>false</super-node>
	<label>VNKR41FL.FRW</label>
	<weight>1065</weight>
	<type>-1</type>
</node>
<node>
	<id>160</id>
	<super-node>false</super-node>
	<label>VNKR41FL.MAP</label>
	<weight>594</weight>
	<type>-1</type>
</node>
<node>
	<id>161</id>
	<super-node>false</super-node>
	<label>VNKR41FL.SAV</label>
	<weight>1210</weight>
	<type>-1</type>
</node>
<node>
	<id>162</id>
	<super-node>false</super-node>
	<label>DHS_LOG.docx</label>
	<weight>85</weight>
	<type>0</type>
</node>
<node>
	<id>163</id>
	<super-node>false</super-node>
	<label>household</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>164</id>
	<super-node>false</super-node>
	<label>VNHR41SV</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>165</id>
	<super-node>false</super-node>
	<label>VNHR41FL.csv</label>
	<weight>7245</weight>
	<type>0</type>
</node>
<node>
	<id>166</id>
	<super-node>false</super-node>
	<label>VNHR41FL.dat</label>
	<weight>7245</weight>
	<type>1</type>
</node>
<node>
	<id>167</id>
	<super-node>false</super-node>
	<label>VNHR41FL.FRQ</label>
	<weight>605</weight>
	<type>-1</type>
</node>
<node>
	<id>168</id>
	<super-node>false</super-node>
	<label>VNHR41FL.FRW</label>
	<weight>605</weight>
	<type>-1</type>
</node>
<node>
	<id>169</id>
	<super-node>false</super-node>
	<label>VNHR41FL.MAP</label>
	<weight>131</weight>
	<type>-1</type>
</node>
<node>
	<id>170</id>
	<super-node>false</super-node>
	<label>VNHR41FL.SAV</label>
	<weight>4157</weight>
	<type>-1</type>
</node>
<node>
	<id>171</id>
	<super-node>false</super-node>
	<label>individual</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>172</id>
	<super-node>false</super-node>
	<label>VNIR41SV</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>173</id>
	<super-node>false</super-node>
	<label>VNIR41FL.csv</label>
	<weight>35253</weight>
	<type>0</type>
</node>
<node>
	<id>174</id>
	<super-node>false</super-node>
	<label>VNIR41FL.dat</label>
	<weight>35253</weight>
	<type>1</type>
</node>
<node>
	<id>175</id>
	<super-node>false</super-node>
	<label>VNIR41FL.DOC</label>
	<weight>60</weight>
	<type>0</type>
</node>
<node>
	<id>176</id>
	<super-node>false</super-node>
	<label>VNIR41FL.FRQ</label>
	<weight>1526</weight>
	<type>-1</type>
</node>
<node>
	<id>177</id>
	<super-node>false</super-node>
	<label>VNIR41FL.FRW</label>
	<weight>1526</weight>
	<type>-1</type>
</node>
<node>
	<id>178</id>
	<super-node>false</super-node>
	<label>VNIR41FL.MAP</label>
	<weight>948</weight>
	<type>-1</type>
</node>
<node>
	<id>179</id>
	<super-node>false</super-node>
	<label>VNIR41FL.SAV</label>
	<weight>19493</weight>
	<type>-1</type>
</node>
<node>
	<id>180</id>
	<super-node>false</super-node>
	<label>VNIR41FL_3_Processed.txt.txt</label>
	<weight>736</weight>
	<type>0</type>
</node>
<node>
	<id>181</id>
	<super-node>false</super-node>
	<label>Recode4DHS.pdf</label>
	<weight>464</weight>
	<type>0</type>
</node>
<node>
	<id>182</id>
	<super-node>false</super-node>
	<label>service availability raw</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>183</id>
	<super-node>false</super-node>
	<label>VNSQ41SV</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>184</id>
	<super-node>false</super-node>
	<label>VNSQ41FL.csv</label>
	<weight>278</weight>
	<type>0</type>
</node>
<node>
	<id>185</id>
	<super-node>false</super-node>
	<label>VNSQ41FL.dat</label>
	<weight>278</weight>
	<type>1</type>
</node>
<node>
	<id>186</id>
	<super-node>false</super-node>
	<label>VNSQ41FL.MAP</label>
	<weight>298</weight>
	<type>-1</type>
</node>
<node>
	<id>187</id>
	<super-node>false</super-node>
	<label>VNSQ41FL.SAV</label>
	<weight>270</weight>
	<type>-1</type>
</node>
<node>
	<id>188</id>
	<super-node>false</super-node>
	<label>VNIR41FL_4_processed.txt</label>
	<weight>804</weight>
	<type>0</type>
</node>
<node>
	<id>189</id>
	<super-node>false</super-node>
	<label>drawoptions.txt</label>
	<weight>1</weight>
	<type>0</type>
</node>
<node>
	<id>190</id>
	<super-node>false</super-node>
	<label>Images</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>191</id>
	<super-node>false</super-node>
	<label>chess.png</label>
	<weight>4</weight>
	<type>2</type>
</node>
<node>
	<id>192</id>
	<super-node>false</super-node>
	<label>clock.png</label>
	<weight>12</weight>
	<type>2</type>
</node>
<node>
	<id>193</id>
	<super-node>false</super-node>
	<label>female.png</label>
	<weight>8</weight>
	<type>2</type>
</node>
<node>
	<id>194</id>
	<super-node>false</super-node>
	<label>folder.png</label>
	<weight>12</weight>
	<type>2</type>
</node>
<node>
	<id>195</id>
	<super-node>false</super-node>
	<label>heart.png</label>
	<weight>7</weight>
	<type>2</type>
</node>
<node>
	<id>196</id>
	<super-node>false</super-node>
	<label>home.png</label>
	<weight>11</weight>
	<type>2</type>
</node>
<node>
	<id>197</id>
	<super-node>false</super-node>
	<label>male.png</label>
	<weight>11</weight>
	<type>2</type>
</node>
<node>
	<id>198</id>
	<super-node>false</super-node>
	<label>stopsign.png</label>
	<weight>4</weight>
	<type>2</type>
</node>
<node>
	<id>199</id>
	<super-node>false</super-node>
	<label>mywork1</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>200</id>
	<super-node>false</super-node>
	<label>property_visualisation.txt</label>
	<weight>1</weight>
	<type>0</type>
</node>
<node>
	<id>201</id>
	<super-node>false</super-node>
	<label>ReadMe.html</label>
	<weight>15</weight>
	<type>3</type>
</node>
<node>
	<id>202</id>
	<super-node>false</super-node>
	<label>run.bat</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>203</id>
	<super-node>false</super-node>
	<label>save1.txt</label>
	<weight>1</weight>
	<type>0</type>
</node>
<node>
	<id>204</id>
	<super-node>false</super-node>
	<label>TabuVis.jar</label>
	<weight>3957</weight>
	<type>4</type>
</node>
<node>
	<id>205</id>
	<super-node>false</super-node>
	<label>Lecture11Materials</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>206</id>
	<super-node>false</super-node>
	<label>Datasources</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>207</id>
	<super-node>false</super-node>
	<label>de_DE-EU</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>208</id>
	<super-node>false</super-node>
	<label>Beispiel - Superstore.tds</label>
	<weight>158</weight>
	<type>-1</type>
</node>
<node>
	<id>209</id>
	<super-node>false</super-node>
	<label>Beispiel - Superstore.xls</label>
	<weight>3164</weight>
	<type>0</type>
</node>
<node>
	<id>210</id>
	<super-node>false</super-node>
	<label>Weltindikatoren.tde</label>
	<weight>307</weight>
	<type>-1</type>
</node>
<node>
	<id>211</id>
	<super-node>false</super-node>
	<label>Weltindikatoren.tds</label>
	<weight>44</weight>
	<type>-1</type>
</node>
<node>
	<id>212</id>
	<super-node>false</super-node>
	<label>en_US-APAC</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>213</id>
	<super-node>false</super-node>
	<label>Sample - APAC Superstore.tds</label>
	<weight>158</weight>
	<type>-1</type>
</node>
<node>
	<id>214</id>
	<super-node>false</super-node>
	<label>Sample - APAC Superstore.xls</label>
	<weight>3536</weight>
	<type>0</type>
</node>
<node>
	<id>215</id>
	<super-node>false</super-node>
	<label>World Indicators.tde</label>
	<weight>306</weight>
	<type>-1</type>
</node>
<node>
	<id>216</id>
	<super-node>false</super-node>
	<label>World Indicators.tds</label>
	<weight>44</weight>
	<type>-1</type>
</node>
<node>
	<id>217</id>
	<super-node>false</super-node>
	<label>en_US-EU</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>218</id>
	<super-node>false</super-node>
	<label>Sample - EU Superstore.tds</label>
	<weight>154</weight>
	<type>-1</type>
</node>
<node>
	<id>219</id>
	<super-node>false</super-node>
	<label>Sample - EU Superstore.xls</label>
	<weight>3176</weight>
	<type>0</type>
</node>
<node>
	<id>220</id>
	<super-node>false</super-node>
	<label>World Indicators.tde</label>
	<weight>306</weight>
	<type>-1</type>
</node>
<node>